### ISSUE TITLE
Add images folder 

### ISSUE THREAD

**Issue by AswinCG2002** [AswinCG2002/Epochzero_ZeroBugs#2]
Add images folder with images required for the website.

**Comment by Ayush-git-dev** [comment]
I’m in 🙋‍♂️

**Comment by Ayush-git-dev** [comment]
![i2](https://user-images.githubusercontent.com/75990868/103471522-920af180-4da7-11eb-88e0-24adb5ebccb3.png)
![i3](https://user-images.githubusercontent.com/75990868/103471523-933c1e80-4da7-11eb-91ca-5c193403fe8a.png)
![icons8-cloud-64](https://user-images.githubusercontent.com/75990868/103471524-93d4b500-4da7-11eb-9fca-1b0cf31c3e9c.png)
![icons8-cloudflare-64](https://user-images.githubusercontent.com/75990868/103471525-93d4b500-4da7-11eb-8d49-a494059d5997.png)
![icons8-c-plus-plus-64](https://user-images.githubusercontent.com/75990868/103471526-946d4b80-4da7-11eb-85eb-8133171437d8.png)
![icons8-customer-support-64](https://user-images.githubusercontent.com/75990868/103471528-946d4b80-4da7-11eb-97d8-08e8c20b8024.png)
![icons8-digital-buddies-64](https://user-images.githubusercontent.com/75990868/103471529-9505e200-4da7-11eb-8711-32f15d4b384b.png)
![icons8-e-commerce-64](https://user-images.githubusercontent.com/75990868/103471530-959e7880-4da7-11eb-90ff-a939ea0d4e30.png)
![icons8-heroku-64](https://user-images.githubusercontent.com/75990868/103471531-959e7880-4da7-11eb-9aa0-907002a35883.png)
![icons8-material-ui-48](https://user-images.githubusercontent.com/75990868/103471532-96370f00-4da7-11eb-85ca-8c8b921659d2.png)
![icons8-matlab-64](https://user-images.githubusercontent.com/75990868/103471534-96cfa580-4da7-11eb-93ad-d742641176ec.png)
![icons8-onedrive-64](https://user-images.githubusercontent.com/75990868/103471536-96cfa580-4da7-11eb-8e64-67234f4aad46.png)
![icons8-shopping-cart-promotion-64](https://user-images.githubusercontent.com/75990868/103471537-97683c00-4da7-11eb-87ff-570080823b36.png)
![icons8-software-64](https://user-images.githubusercontent.com/75990868/103471539-97683c00-4da7-11eb-9dfe-87f87f3edc11.png)
![icons8-website-64](https://user-images.githubusercontent.com/75990868/103471540-9800d280-4da7-11eb-85c4-0d9f05a9a84c.png)
![icons8-xcode-64](https://user-images.githubusercontent.com/75990868/103471541-98996900-4da7-11eb-94b1-95c7b510d8d3.png)
![Logo](https://user-images.githubusercontent.com/75990868/103471542-98996900-4da7-11eb-83e1-8f782a7fc3ec.jpeg)
![poduct bg](https://user-images.githubusercontent.com/75990868/103471543-9931ff80-4da7-11eb-82a0-fdda1d0e803a.png)
![undraw_programmer_imem](https://user-images.githubusercontent.com/75990868/103471544-99ca9600-4da7-11eb-9344-746f26e4ff4a.png)
![web design](https://user-images.githubusercontent.com/75990868/103471545-99ca9600-4da7-11eb-997b-2aa4cb040eda.png)
![4799410](https://user-images.githubusercontent.com/75990868/103471546-9afbc300-4da7-11eb-996e-05801167553d.jpg)

**Comment by Ayush-git-dev** [comment]
[https://github.com/AswinCG2002/Epochzero_ZeroBugs/tree/main/Home%20Page/images](url)

**Comment by Ayush-git-dev** [comment]
![4799410](
![icons8-e-commerce
![poduct bg](https://user-images.githubusercontent.com/75990868/103473808-9395e300-4dc2-11eb-9f39-1c027b2adfb0.png)
![undraw_programmer_imem](https://user-images.githubusercontent.com/75990868/103473809-942e7980-4dc2-11eb-86ec-ed369a371699.png)
![web design](https://user-images.githubusercontent.com/75990868/103473810-94c71000-4dc2-11eb-9888-118276bc849d.png)
![Logo-removebg-preview](https://user-images.githubusercontent.com/75990868/103473807-9395e300-4dc2-11eb-995a-bc2a14920271.png)
-64](https://user-images.githubusercontent.com/75990868/103473796-8f69c580-4dc2-11eb-801e-a2a858061fe6.png)
![icons8-heroku-64](https://user-images.githubusercontent.com/75990868/103473797-90025c00-4dc2-11eb-9aec-d979e6fd1ac5.png)
![icons8-material-ui-48](https://user-images.githubusercontent.com/75990868/103473798-909af280-4dc2-11eb-9a20-0a8b4a1800f4.png)
![icons8-matlab-64](https://user-images.githubusercontent.com/75990868/103473799-909af280-4dc2-11eb-9763-25fac2fd6974.png)
![icons8-onedrive-64](https://user-images.githubusercontent.com/75990868/103473800-91338900-4dc2-11eb-9c65-9828542fc6ae.png)
![icons8-shopping-cart-promotion-64](https://user-images.githubusercontent.com/75990868/103473801-91cc1f80-4dc2-11eb-9043-7a44a642ed19.png)
![icons8-software-64](https://user-images.githubusercontent.com/75990868/103473802-91cc1f80-4dc2-11eb-8181-5b0cc5450e58.png)
![icons8-website-64](https://user-images.githubusercontent.com/75990868/103473803-9264b600-4dc2-11eb-9ca6-7d7e52014d0b.png)
![icons8-xcode-64](https://user-images.githubusercontent.com/75990868/103473805-9264b600-4dc2-11eb-9672-f43804cf76d2.png)
![Logo](https://user-images.githubusercontent.com/75990868/103473806-92fd4c80-4dc2-11eb-9980-d73b2da08a77.jpeg)










![icons8-digital-buddies-64](https://user-images.githubusercontent.com/75990868/103473795-8f69c580-4dc2-11eb-840e-b7e2a28f8fb3.png)
https://user-images.githubusercontent.com/75990868/103473788-8aa51180-4dc2-11eb-9b04-b45e720c6eb0.jpg)
![i2](https://user-images.githubusercontent.com/75990868/103473789-8c6ed500-4dc2-11eb-97d1-6831ff407083.png)
![i3](https://user-images.githubusercontent.com/75990868/103473790-8d076b80-4dc2-11eb-8c33-da4fdda37df3.png)
![icons8-cloud-64](https://user-images.githubusercontent.com/75990868/103473791-8da00200-4dc2-11eb-80fd-e9851b11b501.png)
![icons8-cloudflare-64](https://user-images.githubusercontent.com/75990868/103473792-8e389880-4dc2-11eb-8c62-d616df0f637a.png)
![icons8-c-plus-plus-64](https://user-images.githubusercontent.com/75990868/103473793-8ed12f00-4dc2-11eb-9310-df0c50d5be0e.png)
![icons8-customer-support-64](https://user-images.githubusercontent.com/75990868/103473794-8ed12f00-4dc2-11eb-8786-11f36a68ccf2.png)
